### ISSUE TITLE
Startup file

### ISSUE THREAD

**Issue by xxeen900** [TWIST-X7/Thunder-Grabber#14]
![image](https://user-images.githubusercontent.com/105110880/168198866-123fa221-3ef9-4222-b609-04770b9f9474.png)

Upon testing it on myself and running my pc , the start-up launched this file which was old . How do i remove any hidden files related to start up?

**Comment by TWIST-X7** [comment]
in order to delete the hidden exe go to this path C:\Users\{youruser}"\AppData\Roaming and delete the exe named system32.exe
