### ISSUE TITLE
how to decode

### ISSUE THREAD

**Issue by LocalSmail** [TWIST-X7/Thunder-Grabber#3]
how to decode

**Comment by addi00000** [comment]
![49bde44240fb5824dbcb72e807c962f2--patrick-star-funny-patrick-obrian](https://user-images.githubusercontent.com/81730200/164085143-9e1affd8-1cd9-4800-9048-570a8f9f31f1.jpg)

**Comment by addi00000** [comment]
https://user-images.githubusercontent.com/81730200/164085224-88fdafe2-3d85-4c01-919c-fef7f0e9a19f.mp4

**Comment by addi00000** [comment]
![ezgif-6-5cca6358d62f](https://user-images.githubusercontent.com/81730200/164085330-1d94f90a-311d-4d5d-9631-b043d84b31ef.gif)

**Comment by LocalSmail** [comment]
Replace exec with print so you dont get logged
