### ISSUE TITLE
error and nothing shows up in dist

### ISSUE THREAD

**Issue by Izuyazep** [TWIST-X7/Thunder-Grabber#4]
![image](https://user-images.githubusercontent.com/96847178/164730324-8f1af508-0f6f-4d4e-a721-83bdc4955ffc.png)
![image](https://user-images.githubusercontent.com/96847178/164730406-fe2367ab-8483-4166-8e29-6d3508e317f3.png)

**Comment by TWIST-X7** [comment]
add me on discord TWISTX7#9122
