### ISSUE TITLE
Cryptodome Error 

### ISSUE THREAD

**Issue by tmlegend** [TWIST-X7/Thunder-Grabber#5]
Traceback (most recent call last):
  File "C:\Users\Pc User\AppData\Local\Temp\Thunder\test.py", line 20, in <module>
ModuleNotFoundError: No module named 'Cryptodome'

error installing cryptodome

**Comment by BloodOnTop** [comment]
pip install -r requirements.txt

**Comment by TWIST-X7** [comment]
@tmlegend  Add me on Discord so I can help you TWISTX7#9122

**Comment by TWIST-X7** [comment]
pip install pycryptodomex
