### ISSUE TITLE
I think i did something wrong

### ISSUE THREAD

**Issue by Riparonipepper** [TWIST-X7/Thunder-Grabber#7]
so i got to the point where i put in "start launcher.bat" but then it opened cmd and cmd said "'pip' is not recognized as an internal or external command, operable program or batch file." and "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings" im not sure why though, i have both python 3.8.9 and Git installed any help is much appretiated.

**Comment by BloodOnTop** [comment]
lmfao i dont wanna read this

**Comment by BloodOnTop** [comment]
download python new version and add it to path mate💀

**Comment by acedeu** [comment]
> so i got to the point where i put in "start launcher.bat" but then it opened cmd and cmd said "'pip' is not recognized as an internal or external command, operable program or batch file." and "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings" im not sure why though, i have both python 3.8.9 and Git installed any help is much appretiated.

Add it to path
