### ISSUE TITLE
its me again, sorry

### ISSUE THREAD

**Issue by Riparonipepper** [TWIST-X7/Thunder-Grabber#8]
so i got to the part of the program building the grabber and then it said this.

"Creating Grabber...
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Name\Thunder-Grabber\builder.py", line 105, in <module>
    main()
  File "C:\Users\Name\Thunder-Grabber\builder.py", line 97, in main
    os.remove(f'{grabbername}.spec')
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Grabber.spec'"

i have no clue what this means.
not sure if this is me or the code, probably me so any help would be appreciated.  

![image_2022-04-30_201442836](https://user-images.githubusercontent.com/104666223/166127988-f785823c-d386-4ffc-8296-824d1f66743f.png)
A screenshot if it helps.

**Comment by TWIST-X7** [comment]
add me on discord so i can help you TWISTX7#9122

**Comment by killtango** [comment]
i have a similar problem so could i also add you?

**Comment by FULCOS** [comment]
I have the same problem... Can you give the solution please
